# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Excellence-Through-Accidents
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Excellence Through Accidents gives you software development patterns applied 
  in a Ruby on Rails environment. It cares about subjectively beautiful code 
  and it wants to be a light read.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://excellence-through-accidents.com" # the base hostname & protocol for your site
twitter_username: a5308y
github_username:  a5308y

# Build settings
markdown: kramdown
